import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import Link from "next/link";
import { getAllFilesMetadata } from "../lib/mdx";
import HeaderComponent from "../components/HeaderComponent";
import FooterComponent from "../components/FooterComponent";
import BannerComponent from "../components/BannerComponent";
import AboutComponent from "../components/AboutComponent";
import GaleryComponent from "../components/GaleryComponent";

export default function Home({ posts }) {
    const aboutText = `
    Hi, I am a software engenieer who got caught by marketing and creativity after beeng graduated. 
    As my formation was, I love tecnology, so I try to combine the best of coding, user experience design and digital marketing in my work.
    If you need a job done related with any of those areas, get in touch with me so we can talk.
    `
    return (
        <div className={styles.container}>
            <Head>
                <title>Create Next App</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <link rel="icon" href="/favicon.ico" />
                <link rel="preconnect" href="https://fonts.googleapis.com" />
                <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin></link>
            </Head>

            <main className={styles.main}>
                <HeaderComponent
                    title="@fandres51"
                    titleLink="/"
                    callToAction="Get in touch"
                    callToActionLink="https://linktr.ee/fandres51"
                ></HeaderComponent>
                <div className={styles.upperline}></div>
                <BannerComponent
                    message="Hi, I'm Fabio Andrés Enríquez, a Digital Marketing Student based on Quito, Ec."
                    buttonMessage="Check out my Portfolio"
                    buttonAction="/portfolio"
                ></BannerComponent>
                <div className={styles.about}>
                    <AboutComponent
                        title={"About me"}
                        text={aboutText}
                    ></AboutComponent>
                </div>
                <GaleryComponent></GaleryComponent>
            </main>
            <FooterComponent></FooterComponent>
        </div>
    );
}

export async function getStaticProps() {
    const posts = await getAllFilesMetadata();
    console.log(posts);

    return {
        props: { posts },
    };
}
