import Head from "next/head";
import styles from "../styles/Home.module.css";
import HeaderComponent from "../components/HeaderComponent";
import FooterComponent from "../components/FooterComponent";
import BannerComponent from "../components/BannerComponent";
import AboutComponent from "../components/AboutComponent";
import GaleryComponent from '../components/GaleryComponent';
import PhoneGalery from '../components/PhoneGalery';
import TitleComponent from '../components/TitleComponent';
import { BsArrowRightShort } from 'react-icons/bs';
import Link from "next/link";

export default function Home() {
    const aboutText = `
    Hi, I am a software engenieer who got caught by marketing and creativity after beeng graduated. 
    As my formation was, I love tecnology, so I try to combine the best of coding, user experience design and digital marketing in my work.
    If you need a job done related with any of those areas, get in touch with me so we can talk.
    `
    return (
        <div className={styles.container}>
            <Head>
                <title>Create Next App</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <main className={styles.main}>
                <HeaderComponent
                    title="@fandres51"
                    titleLink="/"
                    callToAction="Get in touch"
                    callToActionLink="https://linktr.ee/fandres51"
                ></HeaderComponent>
                <div className={styles.upperline}></div>
                <BannerComponent
                    message="Hi, I'm Fabio Andrés Enríquez, a Digital Marketing Student based on Quito, Ec."
                    buttonMessage="Check out my Portfolio"
                    buttonAction="/portfolio"
                ></BannerComponent>
                <div className={styles.about}>
                    <AboutComponent
                        title={"About me"}
                        text={aboutText}
                    ></AboutComponent>
                </div>
                <div className={styles.aboutline}></div>
                <div className={styles.previousWork}>
                    <div className={styles.previousWorkTitle}>
                        <TitleComponent
                            title={'My Previous Work'}
                            align={'center'}
                        ></TitleComponent>
                    </div>
                    <div className={styles.bigScreens}>
                        <GaleryComponent></GaleryComponent>
                    </div>
                    <div className={styles.smallScreens}>
                        <PhoneGalery></PhoneGalery>
                    </div>
                    <div>
                        <Link href={'/portfolio'}>
                            <div className={styles.workMessage}>
                                <div className={styles.workMessage}>Check out my full portfolio</div>
                                <BsArrowRightShort size={27} color='#226E93'/>
                            </div>
                        </Link>
                    </div>
                </div>
            </main>
            <FooterComponent></FooterComponent>
        </div>
    );
}

